version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: moye_mongodb
    restart: always
    environment:
      # 필수: 초기 루트 계정 사용자 이름과 비밀번호를 설정합니다.
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "00000531"
      # 선택: 초기 생성할 데이터베이스 이름을 지정합니다.
      MONGO_INITDB_DATABASE: "moye_messages"
    ports:
      - "27017:27017"
    volumes:
      # 공식 문서에서 권장하는 데이터 경로입니다.
      - mongodata:/data/db

volumes:
  mongodata:
